### ISSUE TITLE
Restructure TAG website

### ISSUE THREAD

**Issue by lianmakesthings** [cncf/tag-app-delivery#410]
We want to activate more members of the wider Cloud Native community for the TAG. Specifically, we are aiming for folks who do not want to commit to joining a WG or the general meeting, but are interested in providing individually scoped assistance on specific activities / projects, e.g. using and providing feedback for podtato-head.

To achieve this, we have identified an action that we perceive to be a low-hanging fruit: Restructuring the website to highlight individual activities going on and giving folks easy access to contributing to the TAG without having to commit a lot of time and effort.
```[tasklist]
### Tasks
- [x] Collect projects we want to highlight on the website
- [ ] Mockup of the new structure
- [ ] Write the code
```

**Comment by krumware** [comment]
Hi @lianmakesthings :wave:, happy to help with this!

**Comment by abangser** [comment]
Very big fan of this. I was suggested by Taylor Dolezal that getting the maturity model work on the site may be a great way to drive awareness as well. 

Please let me know if I can help!

**Comment by krumware** [comment]
I'm a big fan of adding clarifying details to enhance the topic (having a strong baseline and then clarifying), as opposed to having details then making concessions. In a way, as a soapbox, this follows a pattern like the w3c and progressive enhancement for web browser platforms https://www.w3.org/wiki/Graceful_degradation_versus_progressive_enhancement. To me, this means we're providing some high level guidance to promote consistency, yet allow implementors to define how their platforms or products meet or exceed those as implementation details. (in a way we see this in the core k8s project, as projects implement support for things like Ingress, yet provide additional opt-in layers like gateways that could eventually also standardize into a new resource type)

When we've discussed around the question of how to involve vendors we've sometimes approached it as "how project/vendor X solves/meets this need", which allows them to promote their details while also promoting the higher-level guidance/concepts.

So I'm definitely a fan of this approach, and it allows us to be inclusive of both vendors and CNCF projects, and still give them a platform for promotion in addition to promoting participation in the WGs.

**Comment by lianmakesthings** [comment]
Love this idea and fully agree with both of you. I think this is a great structure to start with and will also allow us some flexibility for the future.

Let's use [this doc](https://docs.google.com/document/d/1RibiFs3KlQ0FhfaF4X8owQmDzLuN2y4jRnQy3TYp6KI/edit?usp=sharing) to map it out.
I started with some ideas the way I understood your proposal, but I haven't watched the recording yet. Please feel free to edit as you see fit!

**Comment by krumware** [comment]
I would love it if there was a section on the website where we can share/highlight key artifacts/issues/initiatives so that it's easier to make calls for input.
Trying to do that right now with platform maturity model, whitepaper feedback, and the questionnaire, but I find myself digging through issues and docs to grab some of that info.
It should be ok to publish things to guide folks to works in progress, and it would give an easier public resource to share with non-collaborators.

**Comment by abangser** [comment]
+100 to what @krumware said. this was the suggestion from Taylor about how to better engage the ecosystem as well. I took a stab here: https://docs.google.com/document/d/1RibiFs3KlQ0FhfaF4X8owQmDzLuN2y4jRnQy3TYp6KI/edit?disco=AAAAz2BHhcw But would really appreciate your input on this Colin!

**Comment by node** [comment]
This time please support i18n  early  😄  There are many useful things to be worth of translating into more languages.

**Comment by lianmakesthings** [comment]
Hi @node, that's a very good point. Would you be willing to help us with that?

**Comment by node** [comment]
> Hi @node, that's a very good point. Would you be willing to help us with that?

If we continue to use hugo , let me try  !
