### ISSUE TITLE
Tracking issue: Kubecon Chicago prep

### ISSUE THREAD

**Issue by joshgav** [cncf/tag-app-delivery#470]
This issue is to track jobs to be done to prep for the TAG's presence at Kubecon Chicago on Nov 6-9.

We need your help! If you can work on one of these items comment in this issue and chat us up in Slack.

The form for proposing talks and discussion sessions is at <https://docs.google.com/forms/d/1gvkiqCs3WRULcrpdrGZXfjJGWhmpspzByCxuYR7vP_I/>

- [x] Create a signup sheet for booth support and share with TAG leaders and members
- [x] Plan for and order booth swag - stickers, flyers, etc.
- [ ] Coordinate TAG-specific booth crawl on Tuesday evening (?)
- [x] Prepare graphics and slides for the display in our booth
- [x] Collect responses to CFP ([link](https://docs.google.com/forms/d/1gvkiqCs3WRULcrpdrGZXfjJGWhmpspzByCxuYR7vP_I/edit)) and arrange "lightning talk" and/or "birds of a feather" sessions at Monday project meeting
- [x] Collect responses to CFP ([link](https://docs.google.com/forms/d/1gvkiqCs3WRULcrpdrGZXfjJGWhmpspzByCxuYR7vP_I/edit)) and arrange "lightning talk" and/or "birds of a feather" sessions at booth

**Comment by joshgav** [comment]
Here's the signup sheet for booth duty: <https://docs.google.com/spreadsheets/d/1lh5sxiQta5wQEpRf3Rt3-GG-unyQfXhNjbdm59kOIlQ/>. Supporting the booth means you're there and ready to engage folks who have questions about the TAG, our WGs, and CNCF projects related to App Delivery - our regular participants are all qualified.

The signup sheet is open for editing by TAG leaders and for commenting by everyone else. If you can be at the booth for a slot please comment in the appropriate cell and we'll add you officially. Thank you!

Note that we were originally supposed to only have the booth in the evenings, but per [the info on the event site](https://events.linuxfoundation.org/kubecon-cloudnativecon-north-america/program/project-engagement/) we actually have it all day. Nevertheless, I marked the extra times in yellow as I'm not sure we'll have enough folks to support the booth all day.
