### ISSUE TITLE
Evaluation of infrastructure provisioning related topics 

### ISSUE THREAD

**Issue by thschue** [cncf/tag-app-delivery#589]
To deploy applications successfully, there are efforts that often go hand in hand with infrastructure provisioning and deployment. As we see more projects from the infrastructure space in our TAG and identified (at a poll at KubeCon) that we should get more active in this area, there should be first investigations if it makes sense to build a working group for such topics, if there are enough interested people in this and what the potential scope. of the WG could be.

@genpage initiated and volunteered to drive this topic, @angellk and @thschue will support his efforts from the TAG side.

```[tasklist]
### Tasks
- [ ] Find projects that fit into the topic area and reach out
- [ ] Gather potential topics and goals for this interest area
- [ ] Find interested people
- [ ] Reach out to TAG Runtime (if they want to get involved)
- [ ] Try to find out how this relates to the Platforms WG and the mode of operation between these two WGs
```

**Comment by thschue** [comment]
Will assign this to @genpage as soon as possible :-)

**Comment by dani-CO-CN** [comment]
I would be interested in joining the workshop 😁

**Comment by rynowak** [comment]
I'm very interested to participate in this!

**Comment by GenPage** [comment]
Initial conversation with @angellk suggest we rename from "Infrastructure Provisioning" to "Infrastructure Lifecycle". We're working on getting a draft charter up and reaching out to related pending/accepted projects in the ecosystem.

**Comment by graz-dev** [comment]
I would be really interested to partecipate in this working group!

**Comment by mbarr-hrp** [comment]
What's the best way to help with this effort?  Just wait, and follow this issue?

**Comment by GenPage** [comment]
@mbarr-hrp Yes, we will be announcing a charter, slack channel, and regular meetings very soon.

**Comment by GenPage** [comment]
Charter Proposal PR: https://github.com/cncf/tag-app-delivery/pull/691

**Comment by vasu1124** [comment]
@afritzler @lukasfrank @MalteJ
