### ISSUE TITLE
[chore] Update TAG website & tooling to add WG App Dev

### ISSUE THREAD

**Issue by lianmakesthings** [cncf/tag-app-delivery#670]
update all necessary instances on our website & in our tooling to add WG App Dev leadership.
```[tasklist]
### Tasks
- [x] Add to repo (codeowners, collaborators, discussion)
- [ ] Add to website
- [ ] add to community.cncf.io
- [x] add to linkedin
```

**Comment by lianmakesthings** [comment]
https://github.com/cncf/tag-app-delivery/pull/678
