### ISSUE TITLE
German Translation of Platform Maturity Model

### ISSUE THREAD

**Issue by Rotfuks** [cncf/tag-app-delivery#762]
### Motivation
The platforms working groups resources like the Platform Engineering Maturity Model is a great resource that should be available in more languages. For this it needs to be translated. One such translation that definitely has a lot of interest is German. 

### Todo

- [ ] Translate the Platform Engineering Maturity Model into German
- [ ] Review the Platform Engineering Maturity Model in German
- [x] Translate the Platform Glossary into German
- [ ] Review the Platform Glossary in German

### Outcome
- We can share the insights of the Platform Engineering Maturity Model with German speaking target audiences.

**Comment by puja108** [comment]
As we spoke before, I'm in, happy to get assigned and work with @Rotfuks on this

**Comment by Rotfuks** [comment]
Opened a PR for the first draft of the Glossary translation: https://github.com/cncf/tag-app-delivery/pull/798
